# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: poa

on:
  push:
    branches: [ "main" ]
    paths:
      - 'MEVless/**'
      - 'poa/**'
      - '!**/docs/**'
      - '!**/README.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'MEVless/**'
      - 'poa/**'
      - '!**/docs/**'
      - '!**/README.md'

defaults:
  run:
    working-directory: 'poa'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
